spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=${DB_USER:todouser}
spring.datasource.password=${DB_PASSWORD:madeira}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/api-guide